---
stages:
  - build

build:
  stage: build
  image: python:2
  before_script:
    - pip install -U platformio
  script:
    - platformio run
  artifacts:
    paths: [lib]

# vim: set ai et sw=2 ts=2:
