---
stages:
  - build

build:
  stage: build
  image: python:2
  before_script:
    - pip install -U platformio
  script:
    - platformio run
  artifacts:
    name: 32-bubbles-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    paths: [firmware.bin]

# vim: set ai et sw=2 ts=2:
