---
stages:
  - build

build:
  stage: build
  image: python:2
  script:
    - pip install -U platformio
    - platformio run
    - cp .pioenvs/esp32dev/firmware.bin .
  artifacts:
    name: 32-bubbles-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    paths: [firmware.bin]

# vim: set ai et sw=2 ts=2:
